"""initial_schema

Revision ID: 9acf2121a884
Revises: 
Create Date: 2026-08-26 19:25:51.322649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9acf2121a884'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_zh', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('era', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('domains_json', sa.Text(), nullable=False),
    sa.Column('topics_json', sa.Text(), nullable=False),
    sa.Column('dilemmas_json', sa.Text(), nullable=False),
    sa.Column('short_intro', sa.Text(), nullable=False),
    sa.Column('avatar_tone', sa.String(length=64), nullable=False),
    sa.Column('chat_tier', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_living', sa.Boolean(), nullable=False),
    sa.Column('pack_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personas_slug'), ['slug'], unique=True)

    op.create_table('skill_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('skill_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('license_name', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('permissions_json', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('allowlisted', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_configs_skill_key'), ['skill_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('long_memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('persona_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('citation_label', sa.String(length=240), nullable=False),
    sa.Column('license_note', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_persona_id'), ['persona_id'], unique=False)

    op.create_table('visitor_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('visitor_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('persona_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('unresolved_issue', sa.Text(), nullable=True),
    sa.Column('question_streak', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_persona_id'), ['persona_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('citations_json', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'idempotency_key', name='uq_message_idempotency')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('generation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_runs_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('visitor_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('persona_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('source_message_id', sa.String(length=32), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_persona_id'), ['persona_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('safety_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('visitor_id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('matched_rule', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('redacted_excerpt', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "CREATE VIRTUAL TABLE knowledge_documents_fts USING fts5("
        "id UNINDEXED, persona_id UNINDEXED, title, content, tokenize='unicode61')"
    )
    op.execute(
        "CREATE TRIGGER knowledge_documents_ai AFTER INSERT ON knowledge_documents BEGIN "
        "INSERT INTO knowledge_documents_fts(id, persona_id, title, content) "
        "VALUES (new.id, new.persona_id, new.title, new.content); END"
    )
    op.execute(
        "CREATE TRIGGER knowledge_documents_au AFTER UPDATE ON knowledge_documents BEGIN "
        "DELETE FROM knowledge_documents_fts WHERE id = old.id; "
        "INSERT INTO knowledge_documents_fts(id, persona_id, title, content) "
        "VALUES (new.id, new.persona_id, new.title, new.content); END"
    )
    op.execute(
        "CREATE TRIGGER knowledge_documents_ad AFTER DELETE ON knowledge_documents BEGIN "
        "DELETE FROM knowledge_documents_fts WHERE id = old.id; END"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS knowledge_documents_ad")
    op.execute("DROP TRIGGER IF EXISTS knowledge_documents_au")
    op.execute("DROP TRIGGER IF EXISTS knowledge_documents_ai")
    op.execute("DROP TABLE IF EXISTS knowledge_documents_fts")
    op.drop_table('safety_events')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_memories_persona_id'))

    op.drop_table('memories')
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_runs_conversation_id'))

    op.drop_table('generation_runs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_persona_id'))

    op.drop_table('conversations')
    op.drop_table('visitor_sessions')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_persona_id'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skill_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_configs_skill_key'))

    op.drop_table('skill_configs')
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personas_slug'))

    op.drop_table('personas')
    # ### end Alembic commands ###
